#!/bin/bash
# Prio: 1.05

. /usr/lib/openapp-backup/includes/index

###
# This script will set the siteurl to the primary ip of this box

BACKUPDIR=$1
ACTION=$2

run_backup() {
	[ -r /etc/openapp-backup/scripts.d/mysql ] || fatal "You should enable the mysql-module for openapp-backup too"
	[ ! -x /usr/bin/innobackupex ] && fatal "xtrabackup is not installed. See http://openpanel.com/openapp-mysql for instructions"

	set -o pipefail

	OUTPUT=$(innobackupex --defaults-file=/etc/mysql/debian.cnf ${BACKUPDIR})

	echo "${OUTPUT}" | grep -q 'innobackupex: completed OK!' && warning "Innobackupex gave errors. See output: ${OUTPUT}"
}

run_restore() {
	[ ! -x /usr/bin/innobackupex ] && fatal "xtrabackup is not installed. See http://openpanel.com/openapp-mysql for instructions"

	set -o pipefail

	OUTPUT=$(innobackupex --copy-back ${BACKUPDIR})

	echo "${OUTPUT}" | grep -q 'innobackupex: completed OK!' && warning "Innobackupex gave errors. See output: ${OUTPUT}"
	chmod -R mysql:mysql /var/lib/mysql
}

case ${ACTION} in
    backup)
		run_backup
    ;;
    restore)
        run_restore
    ;;
esac
