#!/bin/bash

CONFDIR=/etc/openapp-mysql

fatal() {
    echo "ERROR: $1"
    exit 1
}

[ -z $1 ] && PASSWORD=`pwgen -s 10`
[ "$1" = "stdin" ] && read -p "Please enter your password: " PASSWORD

MYSQL=/usr/bin/mysql
OPTS="--defaults-file=/etc/mysql/debian.cnf mysql -B -N -e"

QUERY="${MYSQL} ${OPTS}"
[ $UID -eq 0 ] || fatal "You need to be root to run this"
[ -z "$PASSWORD" ] && fatal "We don't have a password. Is pwgen installed?"

${QUERY} "GRANT ALL PRIVILEGES ON *.* TO openapp@'localhost' IDENTIFIED BY '${PASSWORD}';" || fatal "Unable to set Mysql password"

mkdir -p ${CONFDIR}/

cat <<EOB > ${CONFDIR}/phpmyadmin.conf
<?php
\$i=0;
\$i++;
\$cfg['Servers'][\$i]['user']          = 'openapp';
\$cfg['Servers'][\$i]['password']      = '${PASSWORD}'; // use here your password
\$cfg['Servers'][\$i]['auth_type']     = 'config';
?>
EOB

cat <<EOB > ${CONFDIR}/openapp.auth.conf
auth.backend = "plain"
auth.backend.plain.userfile = "${CONFDIR}/lighttpd.passwd"
auth.require = ( "/" =>
(
"method" => "basic",
"realm" => "Password protected area",
"require" => "user=openapp"
)
)
EOB

cat <<EOB > ${CONFDIR}/lighttpd.passwd
openapp:${PASSWORD}
EOB

chmod 640 ${CONFDIR}/*
chown www-data:www-data ${CONFDIR}/*

DO_RESTART=no

if [ ! -L /etc/lighttpd/conf-enabled/openapp.auth.conf ]; then
	ln -s ${CONFDIR}/openapp.auth.conf /etc/lighttpd/conf-enabled/openapp.auth.conf
	DO_RESTART=yes
fi

[ -L /var/www/config.inc.php ] || ln -s ${CONFDIR}/phpmyadmin.conf    /var/www/config.inc.php

[ "${DO_RESTART}" = "yes" ] && /etc/init.d/lighttpd restart

echo "${PASSWORD} is your new password"
